name: onPush

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Get Weather
    steps:
      - uses: actions/checkout@v2
      - name: Get Weather
        shell: bash
        run: chmod +x ./src/getWeather.sh && ./src/getWeather.sh
      - name: Create SMS
        shell: bash
        run: |
          smsText=$(cat sms.txt)
          echo "::set-env name=SMS_TEXT::$smsText"
          echo $SMS_TEXT
      - name: 'Sending SMS Notification'
        uses: twilio-labs/actions-sms@v1
        shell: bash
        run: |
          adim="zafer"
        with:
          fromPhoneNumber: ${{ secrets.MSISDN_SENDER }}
          toPhoneNumber: ${{ secrets.MSISDN_RECEIVER }}
          message: $adim
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: sms
          path: sms.txt
